### ISSUE TITLE
`DiagROM`-based tests

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#103]
Implement integration tests using functionality available in [DiagROM](http://blog.retroleum.co.uk/electronics-articles/a-diagnostic-rom-image-for-the-zx-spectrum/) test ROM.

Required testing framework functionality was already implemented (at least partially) in `rustzx-test` crate

- [x] Memory test 48K
- [x] Memory test 128K + Banked memory test (separate DiagROM menu)
- [x] ULA analysis test
- [x] 50Hz NMI interrupt test
- [x] 128K Videobuffer test
- [x] 128K Contention test
