### ISSUE TITLE
Tape loading and control tests

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#104]
In scope of this task the following tests should be added to the `rustzx-test` suite:
- [x] Create simple multi-block  tape (loader block + screen file block should be enough)
- [x] Fast loading of the standard blocks (autoload can be enabled to eliminate need for user input emulation for this test).
- [x] Normal tape loading (disabled autoload and fastload) + check border contents
- [x] Normal tape loading for 128K
- [x] Tape additional controls test - stop and rewind
