### ISSUE TITLE
Sound generation tests

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#105]
- [x] Make simple tape for sound generation test (beeper + AY)
- [ ] Implement sound 48K test
- [ ] Implement sound 128K test
