### ISSUE TITLE
ZX Spectrum 128K implementetion progress tracking

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#23]
Work on 128K implementation was started in develop branch  
- [x] Memory
- [x] Screen validation on bank switch
- [x] Check contentions
- [x] Loading custom 128K ROM
- [x] Window size option
- [x] AY flag
- [x] Mixing Beeper and AY
- [x] Joysticks

**Comment by pacmancoder** [comment]
Development started by fe2b0d8faae91dcf06e22a945a70421b418bbf35 commit.

**Comment by pacmancoder** [comment]
AY chip moved to separate issue #25

**Comment by pacmancoder** [comment]
AY implemented via e4e3513

**Comment by pacmancoder** [comment]
Kempston implemented via 3059a5a5023aaa85b85641d1ce57d5595a20d8fc

**Comment by pacmancoder** [comment]
All things are implemented. Closing.
