### ISSUE TITLE
v1.0 Tracking issue

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#29]
- [x] Drag n drop
- [ ] Palette configuration
- [ ] Config files
- [ ] Tape autoloading
- [ ] Fast save/load
- [ ] App icon with sdl
- [ ] Keys bindings
- [ ] Controller support
- [ ] More snapshot formats

**Comment by petevine** [comment]
Hi, I'm compiling on ARM right now and would like to know if I use a GLES only SDL2 it is going to run fine or is OpenGL still required?

**Comment by pacmancoder** [comment]
I think it must run, if SDL2 allow this. I have no shader code for now, I just using direct copy texture functions from SDL.

**Comment by petevine** [comment]
Yup, running `rustzx` on its own shows drawing is very fast now, so acceleration clearly works. Switching to SDL2 was a great idea! 

I'm unable to run anything else though, I'll open an issue :)

**Comment by pacmancoder** [comment]
Hm, okay. Interesting,  RustZX itself must load any media passed to `--tap`, `--rom` and `--sna` with standard std functions. (Sna anly works with 48k)

If you pass files as `rustzx file` it definitelly will not work. I`ll implement this and drag'n'drop in next release.

**Comment by petevine** [comment]
Hey, it even runs under SDL2 + OpenGL 1.5 (via [glshim](https://github.com/ptitSeb/glshim)) which AFAIK is a first in Rust!

**Comment by pacmancoder** [comment]
Closing. Created separate issues for all version ideas
