### ISSUE TITLE
Tracking issue for Reggister R correct behavior

### ISSUE THREAD

**Issue by pacmancoder** [pacmancoder/rustzx#3]
### Material from [The Undocumented Z80 Documented](http://www.myquest.nl/z80undocumented/)
This is not really an undocumented feature, but a thorough description of it is not easy to find. The R register is a counter that is updated during every Z80 M1 cycle (approximately equivalent to every instruction), so long as DD, FD, ED and CB are to be regarded as separate instructions, so shifted instructions increase R by two. There's an interesting exception: doubly-shifted opcodes, the DD CB and FD CB ones, also increase R by two. LDI increases R by two, LDIR increases it by 2 times BC, as does LDDR etcetera. R is set to zero when the Z80 is reset.

Both LD A,R and LD R,A use the value of R after it has been increased (eg an XOR A/LD R,A sequence sets the value of R to zero, and [reset]/DI/LD A,R sets A to 0x03).

The highest bit of the R register is never changed: this is because in the old days everyone used 16 Kbit chips. Inside the chip the bits where grouped in a 128x128 matrix, needing a 7 bit refresh cycle. Therefore Zilog decided to count only the lowest 7 bits. You can easily check that the R register is really crucial to memory refresh. 
### Implementation progress
- [x] R = 0 on hw reset
- [x] inc R every istruction without prefix
- [x] double inc R on DD,FD prefixed
- [x] double inc R on CB prefixed
- [x] double inc R on DDCB, FDCB prefixed 
- [x] double inc R on ED prefixed
- [x] LD A,R and LD R, A access R after inc [ED prefix group]
- [x] accepting any interrupt inc R by 1

**Comment by pacmancoder** [comment]
Implemented
